steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/social-scribe:${_TAG}'
      - '-t'
      - 'gcr.io/$PROJECT_ID/social-scribe:latest'
      - '.'

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/social-scribe:${_TAG}'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/social-scribe:latest'

  # Deploy migration job (creates or updates), then execute
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'jobs'
      - 'deploy'
      - 'social-scribe-migrate'
      - '--image'
      - 'gcr.io/$PROJECT_ID/social-scribe:${_TAG}'
      - '--region'
      - '${_REGION}'
      - '--command'
      - '/app/bin/migrate'
      - '--set-cloudsql-instances'
      - '$PROJECT_ID:${_REGION}:social-scribe-db'
      - '--service-account'
      - 'social-scribe-runner@$PROJECT_ID.iam.gserviceaccount.com'
      - '--set-secrets'
      - 'DATABASE_URL=DATABASE_URL:latest'

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'jobs'
      - 'execute'
      - 'social-scribe-migrate'
      - '--region'
      - '${_REGION}'
      - '--wait'

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'social-scribe'
      - '--image'
      - 'gcr.io/$PROJECT_ID/social-scribe:${_TAG}'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '4000'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '10'
      - '--service-account'
      - 'social-scribe-runner@$PROJECT_ID.iam.gserviceaccount.com'
      - '--add-cloudsql-instances'
      - '$PROJECT_ID:${_REGION}:social-scribe-db'
      - '--set-env-vars'
      - 'PHX_SERVER=true'
      - '--set-secrets'
      - 'DATABASE_URL=DATABASE_URL:latest,SECRET_KEY_BASE=SECRET_KEY_BASE:latest,GOOGLE_CLIENT_ID=GOOGLE_CLIENT_ID:latest,GOOGLE_CLIENT_SECRET=GOOGLE_CLIENT_SECRET:latest,HUBSPOT_CLIENT_ID=HUBSPOT_CLIENT_ID:latest,HUBSPOT_CLIENT_SECRET=HUBSPOT_CLIENT_SECRET:latest,RECALL_API_KEY=RECALL_API_KEY:latest,RECALL_REGION=RECALL_REGION:latest,GEMINI_API_KEY=GEMINI_API_KEY:latest'

images:
  - 'gcr.io/$PROJECT_ID/social-scribe:${_TAG}'
  - 'gcr.io/$PROJECT_ID/social-scribe:latest'

substitutions:
  _REGION: 'us-central1'
  _TAG: 'latest'

options:
  logging: CLOUD_LOGGING_ONLY
